package main

const (
	boldStart       = "<b>"
	boldEnd         = "</b>"
	boldReplace     = "``"
	italicStart     = "<i>"
	italicEnd       = "</i>"
	italicReplace   = "*"
	resourceDie     = "R"
	resourceText    = "[resource]"
	resourceReplace = ":zresource:"
	meleeDie        = "MD"
	meleeText       = "[melee]"
	meleeReplace    = ":zmelee:"
	rangedDie       = "RD"
	rangedText      = "[ranged]"
	rangedReplace   = ":ranged:"
	focusDie        = "F"
	focusText       = "[focus]"
	focusReplace    = ":focus:"
	specialDie      = "Sp"
	specialText     = "[special]"
	specialReplace  = ":zspecial:"
	disruptDie      = "Dr"
	disruptText     = "[disrupt]"
	disruptReplace  = ":zdisrupt:"
	discardDie      = "Dc"
	discardText     = "[discard]"
	discardReplace  = ":zdiscard:"
	shieldDie       = "Sh"
	shieldText      = "[sheild]"
	shieldReplace   = ":zshield:"
)
